import type { menuConfigType } from "@/type/config";

const menu:menuConfigType[] = [
    {
        label: "特效标绘",
        name: "specialEffectPlot",
        components: [
            {
                label: "矢量标绘",
                show: true,
                img: require("@/assets/cover/specialEffectPlot/drawShape.png"),
                route: "drawShape",
                component: () => import("@/components/example/specialEffectPlot/DrawShape.vue"),
            },
            {
                label: "应急标绘",
                show: true,
                img: require("@/assets/cover/specialEffectPlot/emergencyPlot.png"),
                route: "emergencyPlot",
                component: () => import("@/components/example/specialEffectPlot/EmergencyPlot.vue"),
            },
            {
                label: "聚合标绘",
                show: true,
                img: require("@/assets/cover/specialEffectPlot/primitiveCluster.png"),
                route: "primitiveCluster",
                component: () => import("@/components/example/specialEffectPlot/PrimitiveCluster.vue"),
            },
            {
                label: "广告牌点",
                show: true,
                img: require("@/assets/cover/specialEffectPlot/boardPoint.png"),
                route: "boardPoint",
                component: () => import("@/components/example/specialEffectPlot/BoardPoint.vue"),
            },
            {
                label: "视频点",
                show: true,
                img: require("@/assets/cover/specialEffectPlot/videoPoint.png"),
                route: "videoPoint",
                component: () => import("@/components/example/specialEffectPlot/VideoPoint.vue"),
            },
            {
                label: "文本点",
                show: true,
                img: require("@/assets/cover/specialEffectPlot/labelPoint.png"),
                route: "labelPoint",
                component: () => import("@/components/example/specialEffectPlot/LabelPoint.vue"),
            },
            {
                label: "特效点",
                show: true,
                img: require("@/assets/cover/specialEffectPlot/effectPoint.png"),
                route: "effectPoint",
                component: () => import("@/components/example/specialEffectPlot/EffectPoint.vue"),
            },
            {
                label: "特效线",
                show: true,
                img: require("@/assets/cover/specialEffectPlot/effectLine.png"),
                route: "effectLine",
                component: () => import("@/components/example/specialEffectPlot/EffectLine.vue"),
            },
            {
                label: "穿梭道路",
                show: true,
                img: require("@/assets/cover/specialEffectPlot/streamLine.png"),
                route: "streamLine",
                component: () => import("@/components/example/specialEffectPlot/StreamLine.vue"),
            },
            {
                label: "飞线",
                show: true,
                img: require("@/assets/cover/specialEffectPlot/flightLine.png"),
                route: "flightLine",
                component: () => import("@/components/example/specialEffectPlot/FlightLine.vue"),
            },
            {
                label: "单个云层",
                show: true,
                img: require("@/assets/cover/specialEffectPlot/singleCloud.png"),
                route: "singleCloud",
                component: () => import("@/components/example/specialEffectPlot/SingleCloud.vue"),
            },
            {
                label: "动态墙体",
                show: true,
                img: require("@/assets/cover/specialEffectPlot/dynamicWall.png"),
                route: "dynamicWall",
                component: () => import("@/components/example/specialEffectPlot/DynamicWall.vue"),
            },
            {
                label: "动态标记",
                show: true,
                img: require("@/assets/cover/specialEffectPlot/dynamicMarking.png"),
                route: "dynamicMarking",
                component: () => import("@/components/example/specialEffectPlot/DynamicMarking.vue"),
            },
            {
                label: "静态标记",
                show: true,
                img: require("@/assets/cover/specialEffectPlot/staticMarking.png"),
                route: "staticMarking",
                component: () => import("@/components/example/specialEffectPlot/StaticMarking.vue"),
            },
            {
                label: "圆柱标记",
                show: true,
                img: require("@/assets/cover/specialEffectPlot/cylinderMarking.png"),
                route: "cylinderMarking",
                component: () => import("@/components/example/specialEffectPlot/CylinderMarking.vue"),
            },
            {
                label: "动态渐变圆",
                show: true,
                img: require("@/assets/cover/specialEffectPlot/dynamicGradientCircle.png"),
                route: "dynamicGradientCircle",
                component: () => import("@/components/example/specialEffectPlot/DynamicGradientCircle.vue"),
            },
            {
                label: "光晕扩散圆",
                show: true,
                img: require("@/assets/cover/specialEffectPlot/haloCircle.png"),
                route: "haloCircle",
                component: () => import("@/components/example/specialEffectPlot/HaloCircle.vue"),
            },
            {
                label: "渐变墙体",
                show: true,
                img: require("@/assets/cover/specialEffectPlot/gradientWall.png"),
                route: "gradientWall",
                component: () => import("@/components/example/specialEffectPlot/GradientWall.vue"),
            },
            {
                label: "动态遮罩",
                show: true,
                img: require("@/assets/cover/specialEffectPlot/dynamicMaskPolygon.png"),
                route: "dynamicMaskPolygon",
                component: () => import("@/components/example/specialEffectPlot/DynamicMaskPolygon.vue"),
            },
            {
                label: "区域标注",
                show: true,
                img: require("@/assets/cover/specialEffectPlot/areaLabel.png"),
                route: "areaLabel",
                component: () => import("@/components/example/specialEffectPlot/AreaLabel.vue"),
            },
            {
                label: "行政区标注",
                show: true,
                img: require("@/assets/cover/specialEffectPlot/regionLabel.png"),
                route: "regionLabel",
                component: () => import("@/components/example/specialEffectPlot/RegionLabel.vue"),
            },
            {
                label: "棱柱体",
                show: true,
                img: require("@/assets/cover/specialEffectPlot/boundingBox.png"),
                route: "boundingBox",
                component: () => import("@/components/example/specialEffectPlot/BoundingBox.vue"),
            },
            {
                label: "雷达扫描线",
                show: true,
                img: require("@/assets/cover/specialEffectPlot/radarScanLine.png"),
                route: "radarScanLine",
                component: () => import("@/components/example/specialEffectPlot/RadarScanLine.vue"),
            },
            {
                label: "动态扫描线",
                show: true,
                img: require("@/assets/cover/specialEffectPlot/dynamicScanCircle.png"),
                route: "dynamicScanCircle",
                component: () => import("@/components/example/specialEffectPlot/DynamicScanCircle.vue"),
            },
            {
                label: "扇形扫描圈",
                show: true,
                img: require("@/assets/cover/specialEffectPlot/sectorScan.png"),
                route: "sectorScan",
                component: () => import("@/components/example/specialEffectPlot/SectorScan.vue"),
            },
            {
                label: "雷达扩散圈",
                show: true,
                img: require("@/assets/cover/specialEffectPlot/scanSegment.png"),
                route: "scanSegment",
                component: () => import("@/components/example/specialEffectPlot/ScanSegment.vue"),
            },
            {
                label: "双向扩散圈",
                show: true,
                img: require("@/assets/cover/specialEffectPlot/bidirectDiffuseCircle.png"),
                route: "bidirectDiffuseCircle",
                component: () => import("@/components/example/specialEffectPlot/BidirectDiffuseCircle.vue"),
            },
            {
                label: "电弧特效",
                show: true,
                img: require("@/assets/cover/specialEffectPlot/electricEllipsoid.png"),
                route: "electricEllipsoid",
                component: () => import("@/components/example/specialEffectPlot/ElectricEllipsoid.vue"),
            },
            {
                label: "电光特效",
                show: true,
                img: require("@/assets/cover/specialEffectPlot/electricLightEllipsoid.png"),
                route: "electricLightEllipsoid",
                component: () => import("@/components/example/specialEffectPlot/ElectricLightEllipsoid.vue"),
            },
            {
                label: "球体特效",
                show: true,
                img: require("@/assets/cover/specialEffectPlot/flowEllipsoid.png"),
                route: "flowEllipsoid",
                component: () => import("@/components/example/specialEffectPlot/FlowEllipsoid.vue"),
            },
            {
                label: "渐变填充",
                show: true,
                img: require("@/assets/cover/specialEffectPlot/gradientPolygon.png"),
                route: "gradientPolygon",
                component: () => import("@/components/example/specialEffectPlot/GradientPolygon.vue"),
            },
        ],
    },
    {
        label: "相机视角",
        name: "cameraView",
        components: [
            {
                label: "地区导航",
                show: true,
                img: require("@/assets/cover/cameraView/areaNavigation.png"),
                route: "areaNavigation",
                component: () => import("@/components/example/cameraView/AreaNavigation.vue"),
            },
            {
                label: "路径漫游",
                show: true,
                img: require("@/assets/cover/cameraView/pathRoaming.png"),
                route: "pathRoaming",
                component: () => import("@/components/example/cameraView/PathRoaming.vue"),
            },
            {
                label: "视角限制",
                show: true,
                img: require("@/assets/cover/cameraView/cameraLimit.png"),
                route: "cameraLimit",
                component: () => import("@/components/example/cameraView/CameraLimit.vue"),
            },
            {
                label: "视角书签",
                show: true,
                img: require("@/assets/cover/cameraView/bookmarkManager.png"),
                route: "bookmarkManager",
                component: () => import("@/components/example/cameraView/BookmarkManager.vue"),
            },
            {
                label: "地球自转",
                show: true,
                img: require("@/assets/cover/cameraView/rotation.png"),
                route: "rotation",
                component: () => import("@/components/example/cameraView/Rotation.vue"),
            },
            {
                label: "遮罩图层",
                show: true,
                img: require("@/assets/cover/cameraView/maskLayer.png"),
                route: "maskLayer",
                component: () => import("@/components/example/cameraView/MaskLayer.vue"),
            },
        ]
    },
    {
        label: "数据可视化",
        name: "dataVisualization",
        components: [
            {
                label: "Cesium热力图",
                show: true,
                img: require("@/assets/cover/dataVisualization/cesiumHeatMap.png"),
                route: "cesiumHeatMap",
                component: () => import("@/components/example/dataVisualization/CesiumHeatMap.vue"),
            },
            {
                label: "mapv蜂巢图",
                show: true,
                img: require("@/assets/cover/dataVisualization/beehiveData.png"),
                route: "beehiveData",
                component: () => import("@/components/example/dataVisualization/BeehiveData.vue"),
            },
            {
                label: "mapv方格图",
                show: true,
                img: require("@/assets/cover/dataVisualization/squareGraphData.png"),
                route: "squareGraphData",
                component: () => import("@/components/example/dataVisualization/SquareGraphData.vue"),
            },
            {
                label: "mapv迁徙图",
                show: true,
                img: require("@/assets/cover/dataVisualization/migrateData.png"),
                route: "migrateData",
                component: () => import("@/components/example/dataVisualization/MigrateData.vue"),
            },
            {
                label: "mapv大迁徙图",
                show: true,
                img: require("@/assets/cover/dataVisualization/bigMigrateData.png"),
                route: "bigMigrateData",
                component: () => import("@/components/example/dataVisualization/BigMigrateData.vue"),
            },
            {
                label: "mapv热力图",
                show: true,
                img: require("@/assets/cover/dataVisualization/heatMapData.png"),
                route: "heatMapData",
                component: () => import("@/components/example/dataVisualization/HeatMapData.vue"),
            },
            {
                label: "mapv强力边界图",
                show: true,
                img: require("@/assets/cover/dataVisualization/strongBoundaryData.png"),
                route: "strongBoundaryData",
                component: () => import("@/components/example/dataVisualization/StrongBoundaryData.vue"),
            },
            {
                label: "echarts迁徙图1",
                show: true,
                img: require("@/assets/cover/dataVisualization/echartsMigrateMap1.png"),
                route: "echartsMigrateMap1",
                component: () => import("@/components/example/dataVisualization/EchartsMigrateMap1.vue"),
            },
            {
                label: "echarts迁徙图2",
                show: true,
                img: require("@/assets/cover/dataVisualization/echartsMigrateMap2.png"),
                route: "echartsMigrateMap2",
                component: () => import("@/components/example/dataVisualization/EchartsMigrateMap2.vue"),
            },
            {
                label: "echarts迁徙图3",
                show: true,
                img: require("@/assets/cover/dataVisualization/echartsMigrateMap3.png"),
                route: "echartsMigrateMap3",
                component: () => import("@/components/example/dataVisualization/EchartsMigrateMap3.vue"),
            },
            {
                label: "echarts流出线",
                show: true,
                img: require("@/assets/cover/dataVisualization/echartsOutletLineMap.png"),
                route: "echartsOutletLineMap",
                component: () => import("@/components/example/dataVisualization/EchartsOutletLineMap.vue"),
            },
            {
                label: "echarts流入线",
                show: true,
                img: require("@/assets/cover/dataVisualization/echartsInflowLineMap.png"),
                route: "echartsInflowLineMap",
                component: () => import("@/components/example/dataVisualization/EchartsInflowLineMap.vue"),
            },
            {
                label: "echarts散点图",
                show: true,
                img: require("@/assets/cover/dataVisualization/echartsScatterMap.png"),
                route: "echartsScatterMap",
                component: () => import("@/components/example/dataVisualization/EchartsScatterMap.vue"),
            },
        ]
    },
    {
        label: "空间分析",
        name: "spatialAnalysis",
        components: [
            {
                label: "测量工具",
                show: true,
                img: require("@/assets/cover/spatialAnalysis/measureTool.png"),
                route: "measureTool",
                component: () => import("@/components/example/spatialAnalysis/MeasureTool.vue"),
            },
            {
                label: "二三维视图",
                show: true,
                img: require("@/assets/cover/spatialAnalysis/linkView.png"),
                route: "linkView",
                component: () => import("@/components/example/spatialAnalysis/LinkView.vue"),
            },
            {
                label: "卷帘视图",
                show: true,
                img: require("@/assets/cover/spatialAnalysis/layerSplit.png"),
                route: "layerSplit",
                component: () => import("@/components/example/spatialAnalysis/LayerSplit.vue"),
            },
            {
                label: "鹰眼视图",
                show: true,
                img: require("@/assets/cover/spatialAnalysis/eagleEyeView.png"),
                route: "eagleEyeView",
                component: () => import("@/components/example/spatialAnalysis/EagleEyeView.vue"),
            },
            // {
            //     label: "可视域分析",
            //     show: true,
            //     img: require("@/assets/cover/bePerfecting.png"),
            //     route: "visualFieldAnalysis",
            //     component: () => import("@/components/example/spatialAnalysis/VisualFieldAnalysis.vue"),
            // },
            {
                label: "缓冲区分析",
                show: true,
                img: require("@/assets/cover/spatialAnalysis/bufferAnalysis.png"),
                route: "bufferAnalysis",
                component: () => import("@/components/example/spatialAnalysis/BufferAnalysis.vue"),
            },
            {
                label: "克里金插值",
                show: true,
                img: require("@/assets/cover/spatialAnalysis/krigingInterpolation.png"),
                route: "krigingInterpolation",
                component: () => import("@/components/example/spatialAnalysis/KrigingInterpolation.vue"),
            },
            {
                label: "限高分析",
                show: true,
                img: require("@/assets/cover/spatialAnalysis/heightLimitAnalysis.png"),
                route: "heightLimitAnalysis",
                component: () => import("@/components/example/spatialAnalysis/HeightLimitAnalysis.vue"),
            },
            {
                label: "坡度分析",
                show: true,
                img: require("@/assets/cover/spatialAnalysis/slopeAnalysis.png"),
                route: "slopeAnalysis",
                component: () => import("@/components/example/spatialAnalysis/SlopeAnalysis.vue"),
            },
            {
                label: "等高线分析",
                show: true,
                img: require("@/assets/cover/spatialAnalysis/contourAnalysis.png"),
                route: "contourAnalysis",
                component: () => import("@/components/example/spatialAnalysis/ContourAnalysis.vue"),
            },
            {
                label: "地理网格",
                show: true,
                img: require("@/assets/cover/spatialAnalysis/geoGrid.png"),
                route: "geoGrid",
                component: () => import("@/components/example/spatialAnalysis/GeoGrid.vue"),
            },
            {
                label: "海陆判断",
                show: true,
                img: require("@/assets/cover/spatialAnalysis/pointIsInLand.png"),
                route: "pointIsInLand",
                component: () => import("@/components/example/spatialAnalysis/PointIsInLand.vue"),
            },
            {
                label: "地形开挖",
                show: true,
                img: require("@/assets/cover/spatialAnalysis/surfaceExcavateAnalysis.png"),
                route: "surfaceExcavateAnalysis",
                component: () => import("@/components/example/spatialAnalysis/SurfaceExcavateAnalysis.vue"),
            },
            {
                label: "淹没分析",
                show: true,
                img: require("@/assets/cover/spatialAnalysis/inundationAnalysis.png"),
                route: "inundationAnalysis",
                component: () => import("@/components/example/spatialAnalysis/InundationAnalysis.vue"),
            },
            {
                label: "路径规划",
                show: true,
                img: require("@/assets/cover/spatialAnalysis/pathPlanning.png"),
                route: "pathPlanning",
                component: () => import("@/components/example/spatialAnalysis/PathPlanning.vue"),
            }
        ]
    },
    {
        label: "场景特效",
        name: "sceneEffect",
        components: [
            {
                label: "火焰特效",
                show: true,
                img: require("@/assets/cover/sceneEffect/fireParticle.png"),
                route: "fireParticle",
                component: () => import("@/components/example/sceneEffect/FireParticle.vue"),
            },
            {
                label: "烟雾特效",
                show: true,
                img: require("@/assets/cover/sceneEffect/smokeParticle.png"),
                route: "smokeParticle",
                component: () => import("@/components/example/sceneEffect/SmokeParticle.vue"),
            },
            {
                label: "喷泉特效",
                show: true,
                img: require("@/assets/cover/sceneEffect/fountainParticle.png"),
                route: "fountainParticle",
                component: () => import("@/components/example/sceneEffect/FountainParticle.vue"),
            },
            {
                label: "风场特效",
                show: true,
                img: require("@/assets/cover/sceneEffect/wind3D.png"),
                route: "wind3D",
                component: () => import("@/components/example/sceneEffect/Wind3D.vue"),
            },
            {
                label: "风场特效2",
                show: true,
                img: require("@/assets/cover/sceneEffect/wind3D2.png"),
                route: "wind3D2",
                component: () => import("@/components/example/sceneEffect/Wind3D2.vue"),
            },
            {
                label: "水体特效",
                show: true,
                img: require("@/assets/cover/sceneEffect/waterEffect.png"),
                route: "waterEffect",
                component: () => import("@/components/example/sceneEffect/WaterEffect.vue"),
            },
            {
                label: "全球水体",
                show: true,
                img: require("@/assets/cover/sceneEffect/worldWater.png"),
                route: "worldWater",
                component: () => import("@/components/example/sceneEffect/WorldWater.vue"),
            },
            // {
            //     label: "水面倒影",
            //     show: true,
            //     img: require("@/assets/cover/sceneEffect/waterEffect.png"),
            //     route: "waterInverted",
            //     component: () => import("@/components/example/sceneEffect/WaterInverted.vue"),
            // },
            {
                label: "雨天特效",
                show: true,
                img: require("@/assets/cover/sceneEffect/rainWeather.png"),
                route: "rainWeather",
                component: () => import("@/components/example/sceneEffect/RainWeather.vue"),
            },
            {
                label: "雪天特效",
                show: true,
                img: require("@/assets/cover/sceneEffect/snowWeather.png"),
                route: "snowWeather",
                component: () => import("@/components/example/sceneEffect/SnowWeather.vue"),
            },
            {
                label: "雾天特效",
                show: true,
                img: require("@/assets/cover/sceneEffect/fogWeather.png"),
                route: "fogWeather",
                component: () => import("@/components/example/sceneEffect/FogWeather.vue"),
            },
            {
                label: "天空特效",
                show: true,
                img: require("@/assets/cover/sceneEffect/panoramicSkyBox.png"),
                route: "panoramicSkyBox",
                component: () => import("@/components/example/sceneEffect/PanoramicSkyBox.vue"),
            },
            {
                label: "动态云层",
                show: true,
                img: require("@/assets/cover/sceneEffect/dynamicCloud.png"),
                route: "dynamicCloud",
                component: () => import("@/components/example/sceneEffect/DynamicCloud.vue"),
            },
            {
                label: "地形三角网",
                show: true,
                img: require("@/assets/cover/sceneEffect/triangulationNetwork.png"),
                route: "triangulationNetwork",
                component: () => import("@/components/example/sceneEffect/TriangulationNetwork.vue"),
            },
            {
                label: "地表透明",
                show: true,
                img: require("@/assets/cover/sceneEffect/surfaceTransparency.png"),
                route: "surfaceTransparency",
                component: () => import("@/components/example/sceneEffect/SurfaceTransparency.vue"),
            },
            {
                label: "地形夸张",
                show: true,
                img: require("@/assets/cover/sceneEffect/terrainExaggeration.png"),
                route: "terrainExaggeration",
                component: () => import("@/components/example/sceneEffect/TerrainExaggeration.vue"),
            },
            {
                label: "泛光",
                show: true,
                img: require("@/assets/cover/sceneEffect/floodlight.png"),
                route: "floodlight",
                component: () => import("@/components/example/sceneEffect/Floodlight.vue"),
            },
            {
                label: "灰度",
                show: true,
                img: require("@/assets/cover/sceneEffect/grayscale.png"),
                route: "grayscale",
                component: () => import("@/components/example/sceneEffect/Grayscale.vue"),
            },
            {
                label: "夜视",
                show: true,
                img: require("@/assets/cover/sceneEffect/nightVision.png"),
                route: "nightVision",
                component: () => import("@/components/example/sceneEffect/NightVision.vue"),
            },
            {
                label: "亮度",
                show: true,
                img: require("@/assets/cover/sceneEffect/brightness.png"),
                route: "brightness",
                component: () => import("@/components/example/sceneEffect/Brightness.vue"),
            },
            {
                label: "光照",
                show: true,
                img: require("@/assets/cover/sceneEffect/illumination.png"),
                route: "illumination",
                component: () => import("@/components/example/sceneEffect/Illumination.vue"),
            },
            {
                label: "轮廓",
                show: true,
                img: require("@/assets/cover/sceneEffect/outline.png"),
                route: "outline",
                component: () => import("@/components/example/sceneEffect/Outline.vue"),
            },
            {
                label: "景深",
                show: true,
                img: require("@/assets/cover/sceneEffect/depthField.png"),
                route: "depthField",
                component: () => import("@/components/example/sceneEffect/DepthField.vue"),
            },
            {
                label: "日照阴影",
                show: true,
                img: require("@/assets/cover/sceneEffect/sunshineShadow.png"),
                route: "sunshineShadow",
                component: () => import("@/components/example/sceneEffect/SunshineShadow.vue"),
            },
        ]
    },
    {
        label: "其他功能",
        name: "other",
        components: [
            {
                label: "城阳示范区",
                show: true,
                img: require("@/assets/cover/other/chenYangDemonstration.png"),
                route: "chenYangDemonstration",
                component: () => import("@/components/example/other/ChenYangDemonstration.vue"),
            },
            {
                label: "数据图层",
                show: true,
                img: require("@/assets/cover/other/dataTree.png"),
                route: "dataTree",
                component: () => import("@/components/example/other/DataTree.vue"),
            },
            {
                label: "MVT矢量瓦片",
                show: true,
                img: require("@/assets/cover/other/mvtLayer.png"),
                route: "mvtLayer",
                component: () => import("@/components/example/other/MvtLayer.vue"),
            },
            {
                label: "卫星云图",
                show: true,
                img: require("@/assets/cover/other/cloudMap.png"),
                route: "cloudMap",
                component: () => import("@/components/example/other/CloudMap.vue"),
            },
            {
                label: "卫星态势",
                show: true,
                img: require("@/assets/cover/other/satelliteExtension.png"),
                route: "satelliteExtension",
                component: () => import("@/components/example/other/SatelliteExtension.vue"),
            },
            {
                label: "分割线段",
                show: true,
                img: require("@/assets/cover/other/splitLine.png"),
                route: "splitLine",
                component: () => import("@/components/example/other/SplitLine.vue"),
            },
            {
                label: "分层分户",
                show: true,
                img: require("@/assets/cover/other/householdDivision.png"),
                route: "householdDivision",
                component: () => import("@/components/example/other/householdDivision/index.vue"),
            },
            {
                label: "分层分户预览",
                show: true,
                img: require("@/assets/cover/other/householdPreview.png"),
                route: "householdPreview",
                component: () => import("@/components/example/other/HouseholdPreview.vue"),
            },
            {
                label: "矢量拉伸白模",
                show: true,
                img: require("@/assets/cover/other/vectorWhiteModel2.png"),
                route: "vectorWhiteModel2",
                component: () => import("@/components/example/other/VectorWhiteModel2.vue"),
            },
            {
                label: "矢量拉伸白模(特效)",
                show: true,
                img: require("@/assets/cover/other/vectorWhiteModel.png"),
                route: "vectorWhiteModel",
                component: () => import("@/components/example/other/VectorWhiteModel.vue"),
            },
            {
                label: "区域模型高亮",
                show: true,
                img: require("@/assets/cover/other/modelHighlight.png"),
                route: "modelHighlight",
                component: () => import("@/components/example/other/ModelHighlight.vue"),
            },
            {
                label: "渐变模型效果",
                show: true,
                img: require("@/assets/cover/other/lightShadowModel.png"),
                route: "lightShadowModel",
                component: () => import("@/components/example/other/LightShadowModel.vue"),
            },
            {
                label: "3D描边",
                show: true,
                img: require("@/assets/cover/other/edgeStage.png"),
                route: "edgeStage",
                component: () => import("@/components/example/other/EdgeStage.vue"),
            },
            {
                label: "模型部分可见",
                show: true,
                img: require("@/assets/cover/other/modelPartlyVisible.png"),
                route: "modelPartlyVisible",
                component: () => import("@/components/example/other/ModelPartlyVisible.vue"),
            },
            {
                label: "模型裁剪",
                show: true,
                img: require("@/assets/cover/other/modelClip.png"),
                route: "modelClip",
                component: () => import("@/components/example/other/ModelClip.vue"),
            },
            {
                label: "时序图层",
                show: true,
                img: require("@/assets/cover/other/sequentialPlay.png"),
                route: "sequentialPlay",
                component: () => import("@/components/example/other/SequentialPlay.vue"),
            },
            {
                label: "影像调色",
                show: true,
                img: require("@/assets/cover/other/imageToning.png"),
                route: "imageToning",
                component: () => import("@/components/example/other/ImageToning.vue"),
            },
            {
                label: "立体效果",
                show: true,
                img: require("@/assets/cover/other/stereoeffect.png"),
                route: "stereoeffect",
                component: () => import("@/components/example/other/Stereoeffect.vue"),
            },
        ],
    }
];

export default menu;