import type { menuConfigType } from "@/type/config";

const menu:menuConfigType[] = [
    {
        label: "特效标绘",
        name: "specialEffectPlot",
        components: [
            {
                label: "矢量标绘",
                show: true,
                img: require("@/assets/cover/specialEffectPlot/drawShape.png"),
                route: "drawShape",
                component: () => import("@/components/example/specialEffectPlot/DrawShape.vue"),
            },
            {
                label: "聚合标绘",
                show: true,
                img: require("@/assets/cover/specialEffectPlot/primitiveCluster.png"),
                route: "primitiveCluster",
                component: () => import("@/components/example/specialEffectPlot/PrimitiveCluster.vue"),
            },
            {
                label: "广告牌点",
                show: true,
                img: require("@/assets/cover/specialEffectPlot/boardPoint.png"),
                route: "boardPoint",
                component: () => import("@/components/example/specialEffectPlot/BoardPoint.vue"),
            },
            {
                label: "视频点",
                show: true,
                img: require("@/assets/cover/specialEffectPlot/videoPoint.png"),
                route: "videoPoint",
                component: () => import("@/components/example/specialEffectPlot/VideoPoint.vue"),
            },
            {
                label: "文本点",
                show: true,
                img: require("@/assets/cover/specialEffectPlot/labelPoint.png"),
                route: "labelPoint",
                component: () => import("@/components/example/specialEffectPlot/LabelPoint.vue"),
            },
            {
                label: "特效点",
                show: true,
                img: require("@/assets/cover/specialEffectPlot/effectPoint.png"),
                route: "effectPoint",
                component: () => import("@/components/example/specialEffectPlot/EffectPoint.vue"),
            },
            {
                label: "特效线",
                show: true,
                img: require("@/assets/cover/specialEffectPlot/effectLine.png"),
                route: "effectLine",
                component: () => import("@/components/example/specialEffectPlot/EffectLine.vue"),
            },
            {
                label: "区域标注",
                show: true,
                img: require("@/assets/cover/specialEffectPlot/areaLabel.png"),
                route: "areaLabel",
                component: () => import("@/components/example/specialEffectPlot/AreaLabel.vue"),
            },
            {
                label: "行政区标注",
                show: true,
                img: require("@/assets/cover/specialEffectPlot/regionLabel.png"),
                route: "regionLabel",
                component: () => import("@/components/example/specialEffectPlot/RegionLabel.vue"),
            },
            {
                label: "雷达扫描线",
                show: true,
                img: require("@/assets/cover/specialEffectPlot/radarScanLine.png"),
                route: "radarScanLine",
                component: () => import("@/components/example/specialEffectPlot/RadarScanLine.vue"),
            },
            {
                label: "雷达扫描圈",
                show: true,
                img: require("@/assets/cover/specialEffectPlot/scanSegment.png"),
                route: "scanSegment",
                component: () => import("@/components/example/specialEffectPlot/ScanSegment.vue"),
            },
            {
                label: "渐变填充",
                show: true,
                img: require("@/assets/cover/specialEffectPlot/gradientPolygon.png"),
                route: "gradientPolygon",
                component: () => import("@/components/example/specialEffectPlot/GradientPolygon.vue"),
            },
            {
                label: "模型裁剪",
                show: true,
                img: require("@/assets/cover/specialEffectPlot/modelClip.png"),
                route: "modelClip",
                component: () => import("@/components/example/specialEffectPlot/ModelClip.vue"),
            },
        ],
    },
    {
        label: "相机视角",
        name: "cameraView",
        components: [
            {
                label: "地区导航",
                show: true,
                img: require("@/assets/cover/cameraView/areaNavigation.png"),
                route: "areaNavigation",
                component: () => import("@/components/example/cameraView/AreaNavigation.vue"),
            },
            {
                label: "路径漫游",
                show: true,
                img: require("@/assets/cover/cameraView/pathRoaming.png"),
                route: "pathRoaming",
                component: () => import("@/components/example/cameraView/PathRoaming.vue"),
            },
            {
                label: "视角限制",
                show: true,
                img: require("@/assets/cover/cameraView/cameraLimit.png"),
                route: "cameraLimit",
                component: () => import("@/components/example/cameraView/CameraLimit.vue"),
            },
            {
                label: "视角书签",
                show: true,
                img: require("@/assets/cover/cameraView/bookmarkManager.png"),
                route: "bookmarkManager",
                component: () => import("@/components/example/cameraView/BookmarkManager.vue"),
            },
            {
                label: "地球自转",
                show: true,
                img: require("@/assets/cover/cameraView/rotation.png"),
                route: "rotation",
                component: () => import("@/components/example/cameraView/Rotation.vue"),
            },
            {
                label: "模型部分可见",
                show: true,
                img: require("@/assets/cover/cameraView/modelPartlyVisible.png"),
                route: "modelPartlyVisible",
                component: () => import("@/components/example/cameraView/ModelPartlyVisible.vue"),
            },
        ]
    },
    {
        label: "数据可视化",
        name: "dataVisualization",
        components: [
            {
                label: "Cesium热力图",
                show: true,
                img: require("@/assets/cover/dataVisualization/cesiumHeatMap.png"),
                route: "cesiumHeatMap",
                component: () => import("@/components/example/dataVisualization/CesiumHeatMap.vue"),
            },
            {
                label: "mapv蜂巢图",
                show: true,
                img: require("@/assets/cover/dataVisualization/beehiveData.png"),
                route: "beehiveData",
                component: () => import("@/components/example/dataVisualization/BeehiveData.vue"),
            },
            {
                label: "mapv方格图",
                show: true,
                img: require("@/assets/cover/dataVisualization/squareGraphData.png"),
                route: "squareGraphData",
                component: () => import("@/components/example/dataVisualization/SquareGraphData.vue"),
            },
            {
                label: "mapv迁徙图",
                show: true,
                img: require("@/assets/cover/dataVisualization/migrateData.png"),
                route: "migrateData",
                component: () => import("@/components/example/dataVisualization/MigrateData.vue"),
            },
            {
                label: "mapv大迁徙图",
                show: true,
                img: require("@/assets/cover/dataVisualization/bigMigrateData.png"),
                route: "bigMigrateData",
                component: () => import("@/components/example/dataVisualization/BigMigrateData.vue"),
            },
            {
                label: "mapv热力图",
                show: true,
                img: require("@/assets/cover/dataVisualization/heatMapData.png"),
                route: "heatMapData",
                component: () => import("@/components/example/dataVisualization/HeatMapData.vue"),
            },
            {
                label: "mapv强力边界图",
                show: true,
                img: require("@/assets/cover/dataVisualization/strongBoundaryData.png"),
                route: "strongBoundaryData",
                component: () => import("@/components/example/dataVisualization/StrongBoundaryData.vue"),
            },
            {
                label: "echarts迁徙图1",
                show: true,
                img: require("@/assets/cover/dataVisualization/echartsMigrateMap1.png"),
                route: "echartsMigrateMap1",
                component: () => import("@/components/example/dataVisualization/EchartsMigrateMap1.vue"),
            },
            {
                label: "echarts迁徙图2",
                show: true,
                img: require("@/assets/cover/dataVisualization/echartsMigrateMap2.png"),
                route: "echartsMigrateMap2",
                component: () => import("@/components/example/dataVisualization/EchartsMigrateMap2.vue"),
            },
            {
                label: "echarts迁徙图3",
                show: true,
                img: require("@/assets/cover/dataVisualization/echartsMigrateMap3.png"),
                route: "echartsMigrateMap3",
                component: () => import("@/components/example/dataVisualization/EchartsMigrateMap3.vue"),
            },
            {
                label: "echarts流出线",
                show: true,
                img: require("@/assets/cover/dataVisualization/echartsOutletLineMap.png"),
                route: "echartsOutletLineMap",
                component: () => import("@/components/example/dataVisualization/EchartsOutletLineMap.vue"),
            },
            {
                label: "echarts流入线",
                show: true,
                img: require("@/assets/cover/dataVisualization/echartsInflowLineMap.png"),
                route: "echartsInflowLineMap",
                component: () => import("@/components/example/dataVisualization/EchartsInflowLineMap.vue"),
            },
            {
                label: "echarts散点图",
                show: true,
                img: require("@/assets/cover/dataVisualization/echartsScatterMap.png"),
                route: "echartsScatterMap",
                component: () => import("@/components/example/dataVisualization/EchartsScatterMap.vue"),
            },
        ]
    },
    {
        label: "空间分析",
        name: "spatialAnalysis",
        components: [
            {
                label: "测量工具",
                show: true,
                img: require("@/assets/cover/spatialAnalysis/measureTool.png"),
                route: "measureTool",
                component: () => import("@/components/example/spatialAnalysis/MeasureTool.vue"),
            },
            {
                label: "二三维视图",
                show: true,
                img: require("@/assets/cover/spatialAnalysis/linkView.png"),
                route: "linkView",
                component: () => import("@/components/example/spatialAnalysis/LinkView.vue"),
            },
            {
                label: "卷帘视图",
                show: true,
                img: require("@/assets/cover/spatialAnalysis/layerSplit.png"),
                route: "layerSplit",
                component: () => import("@/components/example/spatialAnalysis/LayerSplit.vue"),
            },
            {
                label: "鹰眼视图",
                show: true,
                img: require("@/assets/cover/spatialAnalysis/eagleEyeView.png"),
                route: "eagleEyeView",
                component: () => import("@/components/example/spatialAnalysis/EagleEyeView.vue"),
            },
            {
                label: "可视域分析",
                show: true,
                img: require("@/assets/cover/bePerfecting.png"),
                route: "visualFieldAnalysis",
                component: () => import("@/components/example/spatialAnalysis/VisualFieldAnalysis.vue"),
            },
            {
                label: "限高分析",
                show: true,
                img: require("@/assets/cover/spatialAnalysis/heightLimitAnalysis.png"),
                route: "heightLimitAnalysis",
                component: () => import("@/components/example/spatialAnalysis/HeightLimitAnalysis.vue"),
            },
            {
                label: "地理网格",
                show: true,
                img: require("@/assets/cover/spatialAnalysis/geoGrid.png"),
                route: "geoGrid",
                component: () => import("@/components/example/spatialAnalysis/GeoGrid.vue"),
            },
            {
                label: "海陆判断",
                show: true,
                img: require("@/assets/cover/spatialAnalysis/pointIsInLand.png"),
                route: "pointIsInLand",
                component: () => import("@/components/example/spatialAnalysis/PointIsInLand.vue"),
            },
            {
                label: "遮罩图层",
                show: true,
                img: require("@/assets/cover/spatialAnalysis/maskLayer.png"),
                route: "maskLayer",
                component: () => import("@/components/example/spatialAnalysis/MaskLayer.vue"),
            },
            {
                label: "地形开挖",
                show: true,
                img: require("@/assets/cover/spatialAnalysis/surfaceExcavate.png"),
                route: "surfaceExcavate",
                component: () => import("@/components/example/spatialAnalysis/SurfaceExcavate.vue"),
            },
            {
                label: "路径规划",
                show: true,
                img: require("@/assets/cover/spatialAnalysis/pathPlanning.png"),
                route: "pathPlanning",
                component: () => import("@/components/example/spatialAnalysis/PathPlanning.vue"),
            }
        ]
    },
    {
        label: "场景特效",
        name: "sceneEffect",
        components: [
            {
                label: "火焰特效",
                show: true,
                img: require("@/assets/cover/sceneEffect/fireParticle.png"),
                route: "fireParticle",
                component: () => import("@/components/example/sceneEffect/FireParticle.vue"),
            },
            {
                label: "烟雾特效",
                show: true,
                img: require("@/assets/cover/sceneEffect/smokeParticle.png"),
                route: "smokeParticle",
                component: () => import("@/components/example/sceneEffect/SmokeParticle.vue"),
            },
            {
                label: "喷泉特效",
                show: true,
                img: require("@/assets/cover/sceneEffect/fountainParticle.png"),
                route: "fountainParticle",
                component: () => import("@/components/example/sceneEffect/FountainParticle.vue"),
            },
            {
                label: "水体特效",
                show: true,
                img: require("@/assets/cover/sceneEffect/waterEffect.png"),
                route: "waterEffect",
                component: () => import("@/components/example/sceneEffect/WaterEffect.vue"),
            },
            {
                label: "雨天特效",
                show: true,
                img: require("@/assets/cover/sceneEffect/rainWeather.png"),
                route: "rainWeather",
                component: () => import("@/components/example/sceneEffect/RainWeather.vue"),
            },
            {
                label: "雪天特效",
                show: true,
                img: require("@/assets/cover/sceneEffect/snowWeather.png"),
                route: "snowWeather",
                component: () => import("@/components/example/sceneEffect/SnowWeather.vue"),
            },
            {
                label: "雾天特效",
                show: true,
                img: require("@/assets/cover/sceneEffect/fogWeather.png"),
                route: "fogWeather",
                component: () => import("@/components/example/sceneEffect/FogWeather.vue"),
            },
            {
                label: "天空特效",
                show: true,
                img: require("@/assets/cover/sceneEffect/panoramicSkyBox.png"),
                route: "panoramicSkyBox",
                component: () => import("@/components/example/sceneEffect/PanoramicSkyBox.vue"),
            },
            {
                label: "地形三角网",
                show: true,
                img: require("@/assets/cover/sceneEffect/triangulationNetwork.png"),
                route: "triangulationNetwork",
                component: () => import("@/components/example/sceneEffect/TriangulationNetwork.vue"),
            },
            {
                label: "地表透明",
                show: true,
                img: require("@/assets/cover/sceneEffect/surfaceTransparency.png"),
                route: "surfaceTransparency",
                component: () => import("@/components/example/sceneEffect/SurfaceTransparency.vue"),
            },
            {
                label: "泛光",
                show: true,
                img: require("@/assets/cover/sceneEffect/floodlight.png"),
                route: "floodlight",
                component: () => import("@/components/example/sceneEffect/Floodlight.vue"),
            },
            {
                label: "灰度",
                show: true,
                img: require("@/assets/cover/sceneEffect/grayscale.png"),
                route: "grayscale",
                component: () => import("@/components/example/sceneEffect/Grayscale.vue"),
            },
            {
                label: "夜视",
                show: true,
                img: require("@/assets/cover/sceneEffect/nightVision.png"),
                route: "nightVision",
                component: () => import("@/components/example/sceneEffect/NightVision.vue"),
            },
            {
                label: "亮度",
                show: true,
                img: require("@/assets/cover/sceneEffect/brightness.png"),
                route: "brightness",
                component: () => import("@/components/example/sceneEffect/Brightness.vue"),
            },
            {
                label: "光照",
                show: true,
                img: require("@/assets/cover/sceneEffect/illumination.png"),
                route: "illumination",
                component: () => import("@/components/example/sceneEffect/Illumination.vue"),
            },
            {
                label: "轮廓",
                show: true,
                img: require("@/assets/cover/sceneEffect/outline.png"),
                route: "outline",
                component: () => import("@/components/example/sceneEffect/Outline.vue"),
            },
            {
                label: "景深",
                show: true,
                img: require("@/assets/cover/sceneEffect/depthField.png"),
                route: "depthField",
                component: () => import("@/components/example/sceneEffect/DepthField.vue"),
            },
            {
                label: "日照阴影",
                show: true,
                img: require("@/assets/cover/sceneEffect/sunshineShadow.png"),
                route: "sunshineShadow",
                component: () => import("@/components/example/sceneEffect/SunshineShadow.vue"),
            },
        ]
    },
];

export default menu;